### ISSUE TITLE
KeyError: 'type'

### ISSUE THREAD

**Issue by MiroStW** [camflint/JourneyToDayOneImporter#5]
Hi there,

I'm trying to use your neat tool, but ran into an error. I'm not familiar with python, but was able to clone the repo & install required modules. Then I got the following error when running `python3 j2d.py Journal ../../journey`:
```
Traceback (most recent call last):
  File "/JourneyToDayOneImporter/j2d.py", line 270, in <module>
    i.run()
  File "/JourneyToDayOneImporter/j2d.py", line 84, in run
    self.print_result(imported_entries)
  File "/JourneyToDayOneImporter/j2d.py", line 252, in print_result
    succeeded_count = len(list(imported_entries))
  File "/JourneyToDayOneImporter/j2d.py", line 194, in import_entries
    flat_entries = list(entries)
  File "/JourneyToDayOneImporter/j2d.py", line 108, in validate_journey_entries
    for raw in raw_entries:
  File "/JourneyToDayOneImporter/j2d.py", line 88, in load_journey_entries
    yield self.load_entry(file)
  File "/JourneyToDayOneImporter/j2d.py", line 99, in load_entry
    entry = self.extract_entry_from_body(body, file)
  File "/JourneyToDayOneImporter/j2d.py", line 105, in extract_entry_from_body
    type=body['type'], timezone=body['timezone'], path=path)
KeyError: 'type'
```

Is there anything I can do to make it work or is it a bug? 

Thanks a lot for your help!
Miro

**Comment by camflint** [comment]
That does indeed look like a bug in processing a particular entry, and/or it's possible that Journey changed their format a bit.

**Comment by MiroStW** [comment]
ah, my particular import is actually from 2017, maybe that could be a problem. Also I am not on a paid plan in day one.

 Is there anything I can do to solve this? Thanks!

**Comment by MiroStW** [comment]
Hello @camflint,

I am happy to report, that I have fixed my problem! It was in fact the old export that was not compatible anymore. I solved it by reinstalling journey on an android device, imported my old export, then re-exported it. The new export worked flawlessly with your tool!! <3

Thanks a lot for this great solution :-)

Best
Miro
